import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillYoutube,
  AiFillHtml5,
  AiFillreact
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import vihar from '../public/fotor_2023-2-19_11_38_51.png'
import proj1 from '../public/website.png'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Vihar Gandhi Protfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 bg-purple-200">
       <section className=" min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-2xl font-burtons">ViharGandhi</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill className="cursor-pointer  text-2xl"/>
            </li>
            <li><a className="bg-zinc-800 text-white px-4 py-2 border-none rounded-md ml-8 font-burtons " href="#">Resume</a></li>
          </ul>
        </nav>
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-purple-800 font-burtons">Vihar Gandhi</h2>
          <h3 className="text-2xl py-2 font-burtons">Developer and always a Learner</h3>
          <p className="text-md py-5 leading-8 text-gray-800 font-burtons">Hi everyone i am Techenthusiast i am currently pursuing my B-tech in Information and techology i like to learn new  technology and also love to educate people on new technologies </p>
        </div>
        <div className="text-5xl flex justify-center gap-16 py-1">
          <a href="https://twitter.com/ViharDumb" className="text-sky-400"><AiFillTwitterCircle/></a>
          <a href="https://www.linkedin.com/in/vihar-gandhi-638957230/" className="text-sky-600"><AiFillLinkedin/></a>
          <a href="https://github.com/ViharGandhi"><AiFillGithub/></a>
          </div>
          <div  className="relative mx-auto bg-purple-500 rounded-full w-60 h-60 mt-20 overflow-hidden" >
            <Image  src={vihar} layout="fill" objectFit="cover"/>
          </div>
       </section>
       <section>
        <div className="text-center mt-10 text-5xl font-burtons text-purple-800">
          <h1>Technologies I Know</h1>
        </div>
        <div className="text-center mt-10 ">
          <h1 className="text-4xl font-burtons text-purple-800">Frontend</h1>
          <ul className="font-burtons">
            <li className="p-2">
              HTML
            </li>
            <li className="p-2">
              CSS
            </li>

            <li className="p-2">
              REACTJS
            </li>
          </ul>
        </div>
        <div className="text-center mt-10">
          <h1 className="text-4xl font-burtons text-purple-800">Backend</h1>
          <ul className="font-burtons">
            <li className="p-2">
              NodeJS
            </li>
            <li className="p-2">
              MongoDB
            </li>
            <li className="p-2">
              Express
            </li>
          </ul>
        </div>
        <div className="text-center mt-10">
          <h1 className="text-4xl font-burtons text-purple-800">Programming Languages</h1>
          <ul className="font-burtons">
            <li className="p-2">C</li>
            <li className="p-2">C++</li>
            <li className="p-2">JavaScript</li>
            <li className="p-2">Solidity</li>
          </ul>
        </div>
        <div className="text-center mt-10">
          <h1 className="text-4xl font-burtons text-purple-800">Web3 Technologies</h1>
          <ul className="font-burtons">
            <li className="p-2">Solidity</li>
            <li className="p-2">EtherJS</li>
            <li className="p-2">Hardhat</li>
            <li className="p-2">Truffle</li>
            <li className="p-2">Web3js</li>
            <li>
              Protocols
              <ul>
                <li>- FileCoin</li>
                <li>- Push</li>
              </ul>
            </li>
          </ul>
        </div>
       </section>
       <section>
        <div className="text-center mt-10">
          <h1 className="text-5xl font-burtons text-purple-800">Achivmets and Hackethons</h1>
          <p className="text-xl font-burtons mt-3">Got 2nd position in smartContract writing competion conducted by GoogleDevelperStudentClub in college</p>
          <p className="text-xl font-burtons mt-3">Participated in 2 Hackethons</p>
          <p className="text-l font-burtons">SheBuilds</p>
          <p className="text-l font-burtons">ETHforall</p>
        </div>
       </section>
       <section>
        <div className="text-center mt-10">
            <h1 className="text-5xl font-burtons text-purple-800">WEB3Projects</h1>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://github.com/ViharGandhi/FullStack-NFT-marketplace">NFT MARKETPLACE</a>
            <div class="flex justify-center">
            <iframe width="885" height="498" src="https://www.youtube.com/embed/k6hfgNsshDQ" title="NFT marketplace" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>
            <br></br>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://github.com/ViharGandhi/ERC20-TOKEN-AND-FAUCET">ERC20 TOKEN AND FAUCET</a>
            <br></br>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://github.com/ViharGandhi/FullStack-CrowdFudning-Dapp">CrowdFunding</a>
            <div class="flex justify-center">
       <iframe class="" width="885" height="498" src="https://www.youtube.com/embed/8yjhHwD4mrY" title="CrowdFundingDAPP" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
            <br></br>
            <div className="text-center mt-10">
            <h1 className="text-5xl font-burtons text-purple-800">WEB2Projects</h1>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://github.com/ViharGandhi/AI-image-web-app">AI-IMAGE-WEB-APP</a>
            <div class="flex justify-center">
            <br></br>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://github.com/ViharGandhi/Real-time-chat-app">RealTime Chat-APP</a>
            <br></br>
   
        
        </div>
            <h1 className="text-5xl font-burtons text-purple-800">Hackethon Projects</h1>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://devfolio.co/projects/team-griffins-6a3d">Property Dispute</a>
            <br></br>
            <a className="text-xl font-burtons mt-3 text-sky-500" href="https://devfolio.co/projects/chainblog-c9b0">Chain Blog</a>
            <p className="text-l font-burtons">More Porjects on my Github HEHEHE</p>
        </div>
      </div>
       </section>
      </main>
    </div>
  );
}
